#!/bin/sh
alias go="docker run --rm -t -i -v \$(pwd):\$(pwd) -w \$(pwd) -e GO111MODULE=on -e GOPROXY=https://goproxy.io --entrypoint /usr/local/go/bin/go golang:1.14-alpine"
echo "*******************************************"
echo "*"`go version`
echo "*******************************************"

git pull
go mod init github.com/turtacn/cloud-prophet
#go mod vendor
#go mod tidy
#go mod verify

go build -v -o ./a  experiments/autopilot/main.go
go build -v -o ./b  experiments/scheduler/main.go

#go build -v -o ./${COMMIT}/cpu  app/ctl/mainCPU.go
#go build -v -o ./${COMMIT}/nnet app/ctl/mainNeural.go
#go build -v -o ./${COMMIT}/ql   app/ctl/mainQl.go
#go build -v -o ./${COMMIT}/     app/ctl/neural.go
