#!/bin/sh
alias go="docker run --rm -t -i -v \$(pwd):\$(pwd) -w \$(pwd) -e GO111MODULE=on -e GOPROXY=https://goproxy.io --entrypoint /usr/local/go/bin/go golang:1.14-alpine"
alias go="docker run --rm -t -i -v \$(pwd):\$(pwd) -w \$(pwd) -e GO111MODULE=on -e GOPROXY=https://goproxy.io --entrypoint /usr/local/go/bin/go golang:1.14"
echo "*******************************************"
echo "*"`go version`
echo "*******************************************"

git pull
#go mod init github.com/turtacn/cloud-prophet
#go mod vendor
#go mod tidy
#go mod verify

go build -mod=mod -v -o ./auto  experiments/autopilot/main.go
go build -mod=mod -v -o ./sched  experiments/scheduler/main.go
